# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LinkedinSwift' do
    pod 'AFNetworking', '>=2.6.3'
    pod 'IOSLinkedInAPIFix', '>= 2.0.3'
end

target 'LinkedinSwiftTests' do
    pod 'AFNetworking', '>=2.6.3'
    pod 'IOSLinkedInAPIFix', '>= 2.0.3'
end

