# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LinkedinSwift' do
  pod 'IOSLinkedInAPI', '= 2.0.0'
end

target 'LinkedinSwiftTests' do

end

